// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk H: presets 24-25.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkH: Record<string, ThemePreset> = {
  'soft-pop': {
    label: 'Soft Pop',
    createdAt: '2025-07-08',
    styles: {
      light: {
        background: '#f7f9f3',
        foreground: '#000000',
        card: '#ffffff',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#4f46e5',
        'primary-foreground': '#ffffff',
        secondary: '#14b8a6',
        'secondary-foreground': '#ffffff',
        muted: '#f0f0f0',
        'muted-foreground': '#333333',
        accent: '#f59e0b',
        'accent-foreground': '#000000',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#000000',
        input: '#737373',
        ring: '#a5b4fc',
        'chart-1': '#4f46e5',
        'chart-2': '#14b8a6',
        'chart-3': '#f59e0b',
        'chart-4': '#ec4899',
        'chart-5': '#22c55e',
        sidebar: '#f7f9f3',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#4f46e5',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f59e0b',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#000000',
        'sidebar-ring': '#a5b4fc',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'DM Sans, sans-serif',
        'font-mono': 'Space Mono, monospace',
        radius: '1rem',
        'shadow-color': '#1a1a1a',
        'shadow-opacity': '0.05',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '0px',
        'letter-spacing': 'normal',
        spacing: '0.25rem',
      },
      dark: {
        background: '#000000',
        foreground: '#ffffff',
        card: '#1a212b',
        'card-foreground': '#ffffff',
        popover: '#1a212b',
        'popover-foreground': '#ffffff',
        primary: '#818cf8',
        'primary-foreground': '#000000',
        secondary: '#2dd4bf',
        'secondary-foreground': '#000000',
        muted: '#333333',
        'muted-foreground': '#cccccc',
        accent: '#fcd34d',
        'accent-foreground': '#000000',
        destructive: '#f87171',
        'destructive-foreground': '#000000',
        border: '#545454',
        input: '#ffffff',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#2dd4bf',
        'chart-3': '#fcd34d',
        'chart-4': '#f472b6',
        'chart-5': '#4ade80',
        sidebar: '#000000',
        'sidebar-foreground': '#ffffff',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#fcd34d',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ffffff',
        'sidebar-ring': '#818cf8',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'DM Sans, sans-serif',
        'font-mono': 'Space Mono, monospace',
        radius: '1rem',
        'shadow-color': '#1a1a1a',
        'shadow-opacity': '0.05',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '0px',
        'letter-spacing': 'normal',
        spacing: '0.25rem',
      },
    },
  },
  'sage-garden': {
    label: 'Sage Garden',
    createdAt: '2025-11-08',
    styles: {
      light: {
        background: '#f8f7f4',
        foreground: '#1a1f2e',
        card: '#ffffff',
        'card-foreground': '#1a1f2e',
        popover: '#ffffff',
        'popover-foreground': '#1a1f2e',
        primary: '#7c9082',
        'primary-foreground': '#ffffff',
        secondary: '#ced4bf',
        'secondary-foreground': '#1a1f2e',
        muted: '#e8e6e1',
        'muted-foreground': '#6b7280',
        accent: '#bfc9bb',
        'accent-foreground': '#1a1f2e',
        destructive: '#c73e3a',
        'destructive-foreground': '#ffffff',
        border: '#e8e6e1',
        input: '#ffffff',
        ring: '#7c9082',
        'chart-1': '#7c9082',
        'chart-2': '#a0aa88',
        'chart-3': '#8b9d83',
        'chart-4': '#6b7280',
        'chart-5': '#e8e6e1',
        sidebar: '#fafaf8',
        'sidebar-foreground': '#1a1f2e',
        'sidebar-primary': '#7c9082',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e8e6e1',
        'sidebar-accent-foreground': '#1a1f2e',
        'sidebar-border': '#e8e6e1',
        'sidebar-ring': '#7c9082',
        'font-sans': 'Antic, ui-sans-serif, sans-serif, system-ui',
        'font-serif': 'Signifier, Georgia, serif',
        'font-mono': 'JetBrains Mono, Courier New, monospace',
        radius: '0.35rem',
        'shadow-color': '#1a1f2e',
        'shadow-opacity': '0.04',
        'shadow-blur': '2px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
        'letter-spacing': '0em',
        spacing: '0.23rem',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#f5f5f5',
        card: '#121212',
        'card-foreground': '#f5f5f5',
        popover: '#121212',
        'popover-foreground': '#f5f5f5',
        primary: '#7c9082',
        'primary-foreground': '#000000',
        secondary: '#1a1a1a',
        'secondary-foreground': '#f5f5f5',
        muted: '#1a1a1a',
        'muted-foreground': '#a0a0a0',
        accent: '#36443a',
        'accent-foreground': '#f5f5f5',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#2a2a2a',
        input: '#121212',
        ring: '#7c9082',
        'chart-1': '#7c9082',
        'chart-2': '#a0aa88',
        'chart-3': '#8b9d83',
        'chart-4': '#6b7280',
        'chart-5': '#5a6b5e',
        sidebar: '#0f0f0f',
        'sidebar-foreground': '#f5f5f5',
        'sidebar-primary': '#7c9082',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1a1a1a',
        'sidebar-accent-foreground': '#f5f5f5',
        'sidebar-border': '#2a2a2a',
        'sidebar-ring': '#7c9082',
        'shadow-color': '#000000',
      },
    },
  },
}
