// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk C: presets 7-10.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkC: Record<string, ThemePreset> = {
  'kodama-grove': {
    label: 'Kodama Grove',
    styles: {
      light: {
        background: '#e4d7b0',
        foreground: '#5c4b3e',
        card: '#e7dbbf',
        'card-foreground': '#5c4b3e',
        popover: '#f3ead2',
        'popover-foreground': '#5c4b3e',
        primary: '#8d9d4f',
        'primary-foreground': '#fdfbf6',
        secondary: '#decea0',
        'secondary-foreground': '#5c4b3e',
        muted: '#decea0',
        'muted-foreground': '#85766a',
        accent: '#dbc894',
        'accent-foreground': '#5c4b3e',
        destructive: '#d98b7e',
        'destructive-foreground': '#faf8f2',
        border: '#b19681',
        input: '#dbc894',
        ring: '#9db18c',
        'chart-1': '#9db18c',
        'chart-2': '#8a9f7b',
        'chart-3': '#bac9b4',
        'chart-4': '#71856a',
        'chart-5': '#5e6e58',
        sidebar: '#e2d1a2',
        'sidebar-foreground': '#5c4b3e',
        'sidebar-primary': '#9db18c',
        'sidebar-primary-foreground': '#fdfbf6',
        'sidebar-accent': '#eae5d9',
        'sidebar-accent-foreground': '#5c4b3e',
        'sidebar-border': '#e5e0d4',
        'sidebar-ring': '#9db18c',
        'font-sans': 'Merriweather, serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.425rem',
        'shadow-color': 'hsl(88 22% 35% / 0.15)',
        'shadow-opacity': '0.15',
        'shadow-blur': '2px',
        'shadow-spread': '0px',
        'shadow-offset-x': '3px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#3a3529',
        foreground: '#ede4d4',
        card: '#413c33',
        'card-foreground': '#ede4d4',
        popover: '#413c33',
        'popover-foreground': '#ede4d4',
        primary: '#8a9f7b',
        'primary-foreground': '#2a2521',
        secondary: '#5a5345',
        'secondary-foreground': '#ede4d4',
        muted: '#4a4439',
        'muted-foreground': '#a8a096',
        accent: '#a18f5c',
        'accent-foreground': '#2a2521',
        destructive: '#b5766a',
        'destructive-foreground': '#f0e9db',
        border: '#5a5345',
        input: '#5a5345',
        ring: '#8a9f7b',
        'chart-1': '#8a9f7b',
        'chart-2': '#9db18c',
        'chart-3': '#71856a',
        'chart-4': '#a18f5c',
        'chart-5': '#5e6e58',
        sidebar: '#3a3529',
        'sidebar-foreground': '#ede4d4',
        'sidebar-primary': '#8a9f7b',
        'sidebar-primary-foreground': '#2a2521',
        'sidebar-accent': '#a18f5c',
        'sidebar-accent-foreground': '#2a2521',
        'sidebar-border': '#5a5345',
        'sidebar-ring': '#8a9f7b',
      },
    },
  },

  'cosmic-night': {
    label: 'Cosmic Night',
    createdAt: '2025-04-04',
    styles: {
      light: {
        background: '#f5f5ff',
        foreground: '#2a2a4a',
        card: '#ffffff',
        'card-foreground': '#2a2a4a',
        popover: '#ffffff',
        'popover-foreground': '#2a2a4a',
        primary: '#6e56cf',
        'primary-foreground': '#ffffff',
        secondary: '#e4dfff',
        'secondary-foreground': '#4a4080',
        muted: '#f0f0fa',
        'muted-foreground': '#6c6c8a',
        accent: '#d8e6ff',
        'accent-foreground': '#2a2a4a',
        destructive: '#ff5470',
        'destructive-foreground': '#ffffff',
        border: '#e0e0f0',
        input: '#e0e0f0',
        ring: '#6e56cf',
        'chart-1': '#6e56cf',
        'chart-2': '#9e8cfc',
        'chart-3': '#5d5fef',
        'chart-4': '#7c75fa',
        'chart-5': '#4740b3',
        radius: '0.5rem',
        sidebar: '#f0f0fa',
        'sidebar-foreground': '#2a2a4a',
        'sidebar-primary': '#6e56cf',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d8e6ff',
        'sidebar-accent-foreground': '#2a2a4a',
        'sidebar-border': '#e0e0f0',
        'sidebar-ring': '#6e56cf',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'JetBrains Mono, monospace',
        'shadow-color': 'hsl(240 30% 25%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '10px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f0f1a',
        foreground: '#e2e2f5',
        card: '#1a1a2e',
        'card-foreground': '#e2e2f5',
        popover: '#1a1a2e',
        'popover-foreground': '#e2e2f5',
        primary: '#a48fff',
        'primary-foreground': '#0f0f1a',
        secondary: '#2d2b55',
        'secondary-foreground': '#c4c2ff',
        muted: '#222244',
        'muted-foreground': '#a0a0c0',
        accent: '#303060',
        'accent-foreground': '#e2e2f5',
        destructive: '#ff5470',
        'destructive-foreground': '#ffffff',
        border: '#303052',
        input: '#303052',
        ring: '#a48fff',
        'chart-1': '#a48fff',
        'chart-2': '#7986cb',
        'chart-3': '#64b5f6',
        'chart-4': '#4db6ac',
        'chart-5': '#ff79c6',
        radius: '0.5rem',
        sidebar: '#1a1a2e',
        'sidebar-foreground': '#e2e2f5',
        'sidebar-primary': '#a48fff',
        'sidebar-primary-foreground': '#0f0f1a',
        'sidebar-accent': '#303060',
        'sidebar-accent-foreground': '#e2e2f5',
        'sidebar-border': '#303052',
        'sidebar-ring': '#a48fff',
      },
    },
  },

  tangerine: {
    label: 'Tangerine',
    createdAt: '2025-04-09',
    styles: {
      light: {
        background: '#e8ebed',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#e05d38',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#d6e4f0',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#dcdfe2',
        input: '#f4f5f7',
        ring: '#e05d38',
        'chart-1': '#86a7c8',
        'chart-2': '#eea591',
        'chart-3': '#5a7ca6',
        'chart-4': '#466494',
        'chart-5': '#334c82',
        sidebar: '#dddfe2',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#e05d38',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d6e4f0',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#e05d38',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.75rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#1c2433',
        foreground: '#e5e5e5',
        card: '#2a3040',
        'card-foreground': '#e5e5e5',
        popover: '#262b38',
        'popover-foreground': '#e5e5e5',
        primary: '#e05d38',
        'primary-foreground': '#ffffff',
        secondary: '#2a303e',
        'secondary-foreground': '#e5e5e5',
        muted: '#2a303e',
        'muted-foreground': '#a3a3a3',
        accent: '#2a3656',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#3d4354',
        input: '#3d4354',
        ring: '#e05d38',
        'chart-1': '#86a7c8',
        'chart-2': '#e6a08f',
        'chart-3': '#5a7ca6',
        'chart-4': '#466494',
        'chart-5': '#334c82',
        sidebar: '#2a303f',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#e05d38',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a3656',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#3d4354',
        'sidebar-ring': '#e05d38',
      },
    },
  },

  'quantum-rose': {
    label: 'Quantum Rose',
    createdAt: '2025-04-03',
    styles: {
      light: {
        background: '#fff0f8',
        foreground: '#91185c',
        card: '#fff7fc',
        'card-foreground': '#91185c',
        popover: '#fff7fc',
        'popover-foreground': '#91185c',
        primary: '#e6067a',
        'primary-foreground': '#ffffff',
        secondary: '#ffd6ff',
        'secondary-foreground': '#91185c',
        muted: '#ffe3f2',
        'muted-foreground': '#c04283',
        accent: '#ffc1e3',
        'accent-foreground': '#91185c',
        destructive: '#d13869',
        'destructive-foreground': '#ffffff',
        border: '#ffc7e6',
        input: '#ffd6ff',
        ring: '#e6067a',
        'chart-1': '#e6067a',
        'chart-2': '#c44b97',
        'chart-3': '#9969b6',
        'chart-4': '#7371bf',
        'chart-5': '#5e84ff',
        sidebar: '#ffedf6',
        'sidebar-foreground': '#91185c',
        'sidebar-primary': '#e6067a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ffc1e3',
        'sidebar-accent-foreground': '#91185c',
        'sidebar-border': '#ffddf0',
        'sidebar-ring': '#e6067a',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Playfair Display, serif',
        'font-mono': 'Space Mono, monospace',
        radius: '0.5rem',
        'shadow-color': 'hsl(330 70% 30% / 0.12)',
        'shadow-opacity': '0.18',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#1a0922',
        foreground: '#ffb3ff',
        card: '#2a1435',
        'card-foreground': '#ffb3ff',
        popover: '#2a1435',
        'popover-foreground': '#ffb3ff',
        primary: '#ff6bef',
        'primary-foreground': '#180518',
        secondary: '#46204f',
        'secondary-foreground': '#ffb3ff',
        muted: '#331941',
        'muted-foreground': '#d67ad6',
        accent: '#5a1f5d',
        'accent-foreground': '#ffb3ff',
        destructive: '#ff2876',
        'destructive-foreground': '#f9f9f9',
        border: '#4a1b5f',
        input: '#46204f',
        ring: '#ff6bef',
        'chart-1': '#ff6bef',
        'chart-2': '#c359e3',
        'chart-3': '#9161ff',
        'chart-4': '#6f73e2',
        'chart-5': '#547aff',
        sidebar: '#1c0d25',
        'sidebar-foreground': '#ffb3ff',
        'sidebar-primary': '#ff6bef',
        'sidebar-primary-foreground': '#180518',
        'sidebar-accent': '#5a1f5d',
        'sidebar-accent-foreground': '#ffb3ff',
        'sidebar-border': '#4a1b5f',
        'sidebar-ring': '#ff6bef',
        'font-sans': 'Quicksand, sans-serif',
        'font-serif': 'Playfair Display, serif',
        'font-mono': 'Space Mono, monospace',
        'shadow-color': 'hsl(300 80% 50% / 0.25)',
      },
    },
  },

  nature: {
    label: 'Nature',
    styles: {
      light: {
        background: '#f8f5f0',
        foreground: '#3e2723',
        card: '#f8f5f0',
        'card-foreground': '#3e2723',
        popover: '#f8f5f0',
        'popover-foreground': '#3e2723',
        primary: '#2e7d32',
        'primary-foreground': '#ffffff',
        secondary: '#e8f5e9',
        'secondary-foreground': '#1b5e20',
        muted: '#f0e9e0',
        'muted-foreground': '#6d4c41',
        accent: '#c8e6c9',
        'accent-foreground': '#1b5e20',
        destructive: '#c62828',
        'destructive-foreground': '#ffffff',
        border: '#e0d6c9',
        input: '#e0d6c9',
        ring: '#2e7d32',
        'chart-1': '#4caf50',
        'chart-2': '#388e3c',
        'chart-3': '#2e7d32',
        'chart-4': '#1b5e20',
        'chart-5': '#0a1f0c',
        radius: '0.5rem',
        sidebar: '#f0e9e0',
        'sidebar-foreground': '#3e2723',
        'sidebar-primary': '#2e7d32',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#c8e6c9',
        'sidebar-accent-foreground': '#1b5e20',
        'sidebar-border': '#e0d6c9',
        'sidebar-ring': '#2e7d32',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Source Code Pro, monospace',
      },
      dark: {
        background: '#1c2a1f',
        foreground: '#f0ebe5',
        card: '#2d3a2e',
        'card-foreground': '#f0ebe5',
        popover: '#2d3a2e',
        'popover-foreground': '#f0ebe5',
        primary: '#4caf50',
        'primary-foreground': '#0a1f0c',
        secondary: '#3e4a3d',
        'secondary-foreground': '#d7e0d6',
        muted: '#252f26',
        'muted-foreground': '#d7cfc4',
        accent: '#388e3c',
        'accent-foreground': '#f0ebe5',
        destructive: '#c62828',
        'destructive-foreground': '#f0ebe5',
        border: '#3e4a3d',
        input: '#3e4a3d',
        ring: '#4caf50',
        'chart-1': '#81c784',
        'chart-2': '#66bb6a',
        'chart-3': '#4caf50',
        'chart-4': '#43a047',
        'chart-5': '#388e3c',
        radius: '0.5rem',
        sidebar: '#1c2a1f',
        'sidebar-foreground': '#f0ebe5',
        'sidebar-primary': '#4caf50',
        'sidebar-primary-foreground': '#0a1f0c',
        'sidebar-accent': '#388e3c',
        'sidebar-accent-foreground': '#f0ebe5',
        'sidebar-border': '#3e4a3d',
        'sidebar-ring': '#4caf50',
      },
    },
  },

  'bold-tech': {
    label: 'Bold Tech',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#312e81',
        card: '#ffffff',
        'card-foreground': '#312e81',
        popover: '#ffffff',
        'popover-foreground': '#312e81',
        primary: '#8b5cf6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f0ff',
        'secondary-foreground': '#4338ca',
        muted: '#f5f3ff',
        'muted-foreground': '#7c3aed',
        accent: '#dbeafe',
        'accent-foreground': '#1e40af',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e0e7ff',
        input: '#e0e7ff',
        ring: '#8b5cf6',
        'chart-1': '#8b5cf6',
        'chart-2': '#7c3aed',
        'chart-3': '#6d28d9',
        'chart-4': '#5b21b6',
        'chart-5': '#4c1d95',
        radius: '0.625rem',
        sidebar: '#f5f3ff',
        'sidebar-foreground': '#312e81',
        'sidebar-primary': '#8b5cf6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#dbeafe',
        'sidebar-accent-foreground': '#1e40af',
        'sidebar-border': '#e0e7ff',
        'sidebar-ring': '#8b5cf6',
        'font-sans': 'Roboto, sans-serif',
        'font-serif': 'Playfair Display, serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': 'hsl(255 86% 66%)',
        'shadow-opacity': '0.2',
        'shadow-blur': '4px',
        'shadow-spread': '0px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#0f172a',
        foreground: '#e0e7ff',
        card: '#1e1b4b',
        'card-foreground': '#e0e7ff',
        popover: '#1e1b4b',
        'popover-foreground': '#e0e7ff',
        primary: '#8b5cf6',
        'primary-foreground': '#ffffff',
        secondary: '#1e1b4b',
        'secondary-foreground': '#e0e7ff',
        muted: '#171447',
        'muted-foreground': '#c4b5fd',
        accent: '#4338ca',
        'accent-foreground': '#e0e7ff',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#2e1065',
        input: '#2e1065',
        ring: '#8b5cf6',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#7c3aed',
        'chart-4': '#6d28d9',
        'chart-5': '#5b21b6',
        radius: '0.625rem',
        sidebar: '#0f172a',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#8b5cf6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#4338ca',
        'sidebar-accent-foreground': '#e0e7ff',
        'sidebar-border': '#2e1065',
        'sidebar-ring': '#8b5cf6',
      },
    },
  },
}
