// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk F: presets 17-22.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkF: Record<string, ThemePreset> = {
  'ocean-breeze': {
    label: 'Ocean Breeze',
    styles: {
      light: {
        background: '#f0f8ff',
        foreground: '#374151',
        card: '#ffffff',
        'card-foreground': '#374151',
        popover: '#ffffff',
        'popover-foreground': '#374151',
        primary: '#22c55e',
        'primary-foreground': '#ffffff',
        secondary: '#e0f2fe',
        'secondary-foreground': '#4b5563',
        muted: '#f3f4f6',
        'muted-foreground': '#6b7280',
        accent: '#d1fae5',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#22c55e',
        'chart-1': '#22c55e',
        'chart-2': '#10b981',
        'chart-3': '#059669',
        'chart-4': '#047857',
        'chart-5': '#065f46',
        radius: '0.5rem',
        sidebar: '#e0f2fe',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#22c55e',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d1fae5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#22c55e',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f172a',
        foreground: '#d1d5db',
        card: '#1e293b',
        'card-foreground': '#d1d5db',
        popover: '#1e293b',
        'popover-foreground': '#d1d5db',
        primary: '#34d399',
        'primary-foreground': '#0f172a',
        secondary: '#2d3748',
        'secondary-foreground': '#a1a1aa',
        muted: '#19212e',
        'muted-foreground': '#6b7280',
        accent: '#374151',
        'accent-foreground': '#a1a1aa',
        destructive: '#ef4444',
        'destructive-foreground': '#0f172a',
        border: '#4b5563',
        input: '#4b5563',
        ring: '#34d399',
        'chart-1': '#34d399',
        'chart-2': '#2dd4bf',
        'chart-3': '#22c55e',
        'chart-4': '#10b981',
        'chart-5': '#059669',
        radius: '0.5rem',
        sidebar: '#1e293b',
        'sidebar-foreground': '#d1d5db',
        'sidebar-primary': '#34d399',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#a1a1aa',
        'sidebar-border': '#4b5563',
        'sidebar-ring': '#34d399',
      },
    },
  },
  'retro-arcade': {
    label: 'Retro Arcade',
    styles: {
      light: {
        background: '#fdf6e3',
        foreground: '#073642',
        card: '#eee8d5',
        'card-foreground': '#073642',
        popover: '#eee8d5',
        'popover-foreground': '#073642',
        primary: '#d33682',
        'primary-foreground': '#ffffff',
        secondary: '#2aa198',
        'secondary-foreground': '#ffffff',
        muted: '#93a1a1',
        'muted-foreground': '#073642',
        accent: '#cb4b16',
        'accent-foreground': '#ffffff',
        destructive: '#dc322f',
        'destructive-foreground': '#ffffff',
        border: '#839496',
        input: '#839496',
        ring: '#d33682',
        'chart-1': '#268bd2',
        'chart-2': '#2aa198',
        'chart-3': '#d33682',
        'chart-4': '#cb4b16',
        'chart-5': '#dc322f',
        radius: '0.25rem',
        sidebar: '#fdf6e3',
        'sidebar-foreground': '#073642',
        'sidebar-primary': '#d33682',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2aa198',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#839496',
        'sidebar-ring': '#d33682',
        'font-sans': 'Outfit, sans-serif',
        'font-mono': 'Space Mono, monospace',
        'shadow-color': 'hsl(196 83% 10%)',
        'shadow-opacity': '0.15',
        'shadow-blur': '4px',
        'shadow-spread': '0px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#002b36',
        foreground: '#93a1a1',
        card: '#073642',
        'card-foreground': '#93a1a1',
        popover: '#073642',
        'popover-foreground': '#93a1a1',
        primary: '#d33682',
        'primary-foreground': '#ffffff',
        secondary: '#2aa198',
        'secondary-foreground': '#ffffff',
        muted: '#586e75',
        'muted-foreground': '#93a1a1',
        accent: '#cb4b16',
        'accent-foreground': '#ffffff',
        destructive: '#dc322f',
        'destructive-foreground': '#ffffff',
        border: '#586e75',
        input: '#586e75',
        ring: '#d33682',
        'chart-1': '#268bd2',
        'chart-2': '#2aa198',
        'chart-3': '#d33682',
        'chart-4': '#cb4b16',
        'chart-5': '#dc322f',
        radius: '0.25rem',
        sidebar: '#002b36',
        'sidebar-foreground': '#93a1a1',
        'sidebar-primary': '#d33682',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2aa198',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#586e75',
        'sidebar-ring': '#d33682',
      },
    },
  },

  'midnight-bloom': {
    label: 'Midnight Bloom',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#6c5ce7',
        'primary-foreground': '#ffffff',
        secondary: '#a1c9f2',
        'secondary-foreground': '#333333',
        muted: '#c9c4b5',
        'muted-foreground': '#6e6e6e',
        accent: '#8b9467',
        'accent-foreground': '#ffffff',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d4d4d4',
        input: '#d4d4d4',
        ring: '#6c5ce7',
        'chart-1': '#6c5ce7',
        'chart-2': '#8e44ad',
        'chart-3': '#4b0082',
        'chart-4': '#6495ed',
        'chart-5': '#4682b4',
        radius: '0.5rem',
        sidebar: '#f9f9f9',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#6c5ce7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#8b9467',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#d4d4d4',
        'sidebar-ring': '#6c5ce7',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Playfair Display, serif',
        'font-mono': 'Source Code Pro, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '10px',
        'shadow-spread': '-2px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '5px',
      },
      dark: {
        background: '#1a1d23',
        foreground: '#e5e5e5',
        card: '#2f3436',
        'card-foreground': '#e5e5e5',
        popover: '#2f3436',
        'popover-foreground': '#e5e5e5',
        primary: '#6c5ce7',
        'primary-foreground': '#ffffff',
        secondary: '#4b0082',
        'secondary-foreground': '#e5e5e5',
        muted: '#444444',
        'muted-foreground': '#a3a3a3',
        accent: '#6495ed',
        'accent-foreground': '#e5e5e5',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#444444',
        input: '#444444',
        ring: '#6c5ce7',
        'chart-1': '#6c5ce7',
        'chart-2': '#8e44ad',
        'chart-3': '#4b0082',
        'chart-4': '#6495ed',
        'chart-5': '#4682b4',
        radius: '0.5rem',
        sidebar: '#1a1d23',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#6c5ce7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#6495ed',
        'sidebar-accent-foreground': '#e5e5e5',
        'sidebar-border': '#444444',
        'sidebar-ring': '#6c5ce7',
      },
    },
  },
  candyland: {
    label: 'Candyland',
    styles: {
      light: {
        background: '#f7f9fa',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#ffc0cb',
        'primary-foreground': '#000000',
        secondary: '#87ceeb',
        'secondary-foreground': '#000000',
        muted: '#ddd9c4',
        'muted-foreground': '#6e6e6e',
        accent: '#ffff00',
        'accent-foreground': '#000000',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d4d4d4',
        input: '#d4d4d4',
        ring: '#ffc0cb',
        'chart-1': '#ffc0cb',
        'chart-2': '#87ceeb',
        'chart-3': '#ffff00',
        'chart-4': '#ff99cc',
        'chart-5': '#33cc33',
        radius: '0.5rem',
        sidebar: '#f7f9fa',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#ffc0cb',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#ffff00',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#d4d4d4',
        'sidebar-ring': '#ffc0cb',
        'font-sans': 'Poppins, sans-serif',
        'font-mono': 'Roboto Mono, monospace',
      },
      dark: {
        background: '#1a1d23',
        foreground: '#e5e5e5',
        card: '#2f3436',
        'card-foreground': '#e5e5e5',
        popover: '#2f3436',
        'popover-foreground': '#e5e5e5',
        primary: '#ff99cc',
        'primary-foreground': '#000000',
        secondary: '#33cc33',
        'secondary-foreground': '#000000',
        muted: '#444444',
        'muted-foreground': '#a3a3a3',
        accent: '#87ceeb',
        'accent-foreground': '#000000',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#444444',
        input: '#444444',
        ring: '#ff99cc',
        'chart-1': '#ff99cc',
        'chart-2': '#33cc33',
        'chart-3': '#87ceeb',
        'chart-4': '#ffff00',
        'chart-5': '#ffcc00',
        radius: '0.5rem',
        sidebar: '#1a1d23',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#ff99cc',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#87ceeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#444444',
        'sidebar-ring': '#ff99cc',
      },
    },
  },
  'northern-lights': {
    label: 'Northern Lights',
    styles: {
      light: {
        background: '#f9f9fa',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#34a85a',
        'primary-foreground': '#ffffff',
        secondary: '#6495ed',
        'secondary-foreground': '#ffffff',
        muted: '#ddd9c4',
        'muted-foreground': '#6e6e6e',
        accent: '#66d9ef',
        'accent-foreground': '#333333',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d4d4d4',
        input: '#d4d4d4',
        ring: '#34a85a',
        'chart-1': '#34a85a',
        'chart-2': '#6495ed',
        'chart-3': '#66d9ef',
        'chart-4': '#4682b4',
        'chart-5': '#1a9641',
        radius: '0.5rem',
        sidebar: '#f9f9fa',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#34a85a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#66d9ef',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#d4d4d4',
        'sidebar-ring': '#34a85a',
        'font-sans': 'Plus Jakarta Sans, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
      },
      dark: {
        background: '#1a1d23',
        foreground: '#e5e5e5',
        card: '#2f3436',
        'card-foreground': '#e5e5e5',
        popover: '#2f3436',
        'popover-foreground': '#e5e5e5',
        primary: '#34a85a',
        'primary-foreground': '#ffffff',
        secondary: '#4682b4',
        'secondary-foreground': '#e5e5e5',
        muted: '#444444',
        'muted-foreground': '#a3a3a3',
        accent: '#6495ed',
        'accent-foreground': '#e5e5e5',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#444444',
        input: '#444444',
        ring: '#34a85a',
        'chart-1': '#34a85a',
        'chart-2': '#4682b4',
        'chart-3': '#6495ed',
        'chart-4': '#66d9ef',
        'chart-5': '#1a9641',
        radius: '0.5rem',
        sidebar: '#1a1d23',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#34a85a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#6495ed',
        'sidebar-accent-foreground': '#e5e5e5',
        'sidebar-border': '#444444',
        'sidebar-ring': '#34a85a',
      },
    },
  },
  'vintage-paper': {
    label: 'Vintage Paper',
    styles: {
      light: {
        background: '#f5f1e6',
        foreground: '#4a3f35',
        card: '#fffcf5',
        'card-foreground': '#4a3f35',
        popover: '#fffcf5',
        'popover-foreground': '#4a3f35',
        primary: '#a67c52',
        'primary-foreground': '#ffffff',
        secondary: '#e2d8c3',
        'secondary-foreground': '#5c4d3f',
        muted: '#ece5d8',
        'muted-foreground': '#7d6b56',
        accent: '#d4c8aa',
        'accent-foreground': '#4a3f35',
        destructive: '#b54a35',
        'destructive-foreground': '#ffffff',
        border: '#dbd0ba',
        input: '#dbd0ba',
        ring: '#a67c52',
        'chart-1': '#a67c52',
        'chart-2': '#8d6e4c',
        'chart-3': '#735a3a',
        'chart-4': '#b3906f',
        'chart-5': '#c0a080',
        radius: '0.25rem',
        sidebar: '#ece5d8',
        'sidebar-foreground': '#4a3f35',
        'sidebar-primary': '#a67c52',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d4c8aa',
        'sidebar-accent-foreground': '#4a3f35',
        'sidebar-border': '#dbd0ba',
        'sidebar-ring': '#a67c52',
        'font-sans': 'Libre Baskerville, serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(28 13% 20%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#2d2621',
        foreground: '#ece5d8',
        card: '#3a322c',
        'card-foreground': '#ece5d8',
        popover: '#3a322c',
        'popover-foreground': '#ece5d8',
        primary: '#c0a080',
        'primary-foreground': '#2d2621',
        secondary: '#4a4039',
        'secondary-foreground': '#ece5d8',
        muted: '#312b26',
        'muted-foreground': '#c5bcac',
        accent: '#59493e',
        'accent-foreground': '#ece5d8',
        destructive: '#b54a35',
        'destructive-foreground': '#ffffff',
        border: '#4a4039',
        input: '#4a4039',
        ring: '#c0a080',
        'chart-1': '#c0a080',
        'chart-2': '#b3906f',
        'chart-3': '#a67c52',
        'chart-4': '#8d6e4c',
        'chart-5': '#735a3a',
        radius: '0.25rem',
        sidebar: '#2d2621',
        'sidebar-foreground': '#ece5d8',
        'sidebar-primary': '#c0a080',
        'sidebar-primary-foreground': '#2d2621',
        'sidebar-accent': '#59493e',
        'sidebar-accent-foreground': '#ece5d8',
        'sidebar-border': '#4a4039',
        'sidebar-ring': '#c0a080',
      },
    },
  },
  'sunset-horizon': {
    label: 'Sunset Horizon',
    styles: {
      light: {
        background: '#fff9f5',
        foreground: '#3d3436',
        card: '#ffffff',
        'card-foreground': '#3d3436',
        popover: '#ffffff',
        'popover-foreground': '#3d3436',
        primary: '#ff7e5f',
        'primary-foreground': '#ffffff',
        secondary: '#ffedea',
        'secondary-foreground': '#b35340',
        muted: '#fff0eb',
        'muted-foreground': '#78716C',
        accent: '#feb47b',
        'accent-foreground': '#3d3436',
        destructive: '#e63946',
        'destructive-foreground': '#ffffff',
        border: '#ffe0d6',
        input: '#ffe0d6',
        ring: '#ff7e5f',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        radius: '0.625rem',
        sidebar: '#fff0eb',
        'sidebar-foreground': '#3d3436',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#3d3436',
        'sidebar-border': '#ffe0d6',
        'sidebar-ring': '#ff7e5f',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Ubuntu Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.09',
        'shadow-blur': '12px',
        'shadow-spread': '-3px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '6px',
      },
      dark: {
        background: '#2a2024',
        foreground: '#f2e9e4',
        card: '#392f35',
        'card-foreground': '#f2e9e4',
        popover: '#392f35',
        'popover-foreground': '#f2e9e4',
        primary: '#ff7e5f',
        'primary-foreground': '#ffffff',
        secondary: '#463a41',
        'secondary-foreground': '#f2e9e4',
        muted: '#30272c',
        'muted-foreground': '#d7c6bc',
        accent: '#feb47b',
        'accent-foreground': '#2a2024',
        destructive: '#e63946',
        'destructive-foreground': '#ffffff',
        border: '#463a41',
        input: '#463a41',
        ring: '#ff7e5f',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        radius: '0.625rem',
        sidebar: '#2a2024',
        'sidebar-foreground': '#f2e9e4',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#2a2024',
        'sidebar-border': '#463a41',
        'sidebar-ring': '#ff7e5f',
      },
    },
  },
}
