// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk D: presets 11-13.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkD: Record<string, ThemePreset> = {
  'elegant-luxury': {
    label: 'Elegant Luxury',
    styles: {
      light: {
        background: '#faf7f5',
        foreground: '#1a1a1a',
        card: '#faf7f5',
        'card-foreground': '#1a1a1a',
        popover: '#faf7f5',
        'popover-foreground': '#1a1a1a',
        primary: '#9b2c2c',
        'primary-foreground': '#ffffff',
        secondary: '#fdf2d6',
        'secondary-foreground': '#805500',
        muted: '#f0ebe8',
        'muted-foreground': '#57534e',
        accent: '#fef3c7',
        'accent-foreground': '#7f1d1d',
        destructive: '#991b1b',
        'destructive-foreground': '#ffffff',
        border: '#f5e8d2',
        input: '#f5e8d2',
        ring: '#9b2c2c',
        'chart-1': '#b91c1c',
        'chart-2': '#9b2c2c',
        'chart-3': '#7f1d1d',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        radius: '0.375rem',
        sidebar: '#f0ebe8',
        'sidebar-foreground': '#1a1a1a',
        'sidebar-primary': '#9b2c2c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef3c7',
        'sidebar-accent-foreground': '#7f1d1d',
        'sidebar-border': '#f5e8d2',
        'sidebar-ring': '#9b2c2c',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Libre Baskerville, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 63% 18%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '16px',
        'shadow-spread': '-2px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#1c1917',
        foreground: '#f5f5f4',
        card: '#292524',
        'card-foreground': '#f5f5f4',
        popover: '#292524',
        'popover-foreground': '#f5f5f4',
        primary: '#b91c1c',
        'primary-foreground': '#faf7f5',
        secondary: '#92400e',
        'secondary-foreground': '#fef3c7',
        muted: '#1f1c1a',
        'muted-foreground': '#d6d3d1',
        accent: '#b45309',
        'accent-foreground': '#fef3c7',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#44403c',
        input: '#44403c',
        ring: '#b91c1c',
        'chart-1': '#f87171',
        'chart-2': '#ef4444',
        'chart-3': '#dc2626',
        'chart-4': '#fbbf24',
        'chart-5': '#f59e0b',
        radius: '0.375rem',
        sidebar: '#1c1917',
        'sidebar-foreground': '#f5f5f4',
        'sidebar-primary': '#b91c1c',
        'sidebar-primary-foreground': '#faf7f5',
        'sidebar-accent': '#b45309',
        'sidebar-accent-foreground': '#fef3c7',
        'sidebar-border': '#44403c',
        'sidebar-ring': '#b91c1c',
      },
    },
  },

  'amber-minimal': {
    label: 'Amber Minimal',
    createdAt: '2025-04-27',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#262626',
        card: '#ffffff',
        'card-foreground': '#262626',
        popover: '#ffffff',
        'popover-foreground': '#262626',
        primary: '#f59e0b',
        'primary-foreground': '#000000',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#fffbeb',
        'accent-foreground': '#92400e',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#f59e0b',
        'chart-1': '#f59e0b',
        'chart-2': '#d97706',
        'chart-3': '#b45309',
        'chart-4': '#92400e',
        'chart-5': '#78350f',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#262626',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fffbeb',
        'sidebar-accent-foreground': '#92400e',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#f59e0b',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.375rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#f59e0b',
        'primary-foreground': '#000000',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#92400e',
        'accent-foreground': '#fde68a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#f59e0b',
        'chart-1': '#fbbf24',
        'chart-2': '#d97706',
        'chart-3': '#92400e',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        sidebar: '#0f0f0f',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#92400e',
        'sidebar-accent-foreground': '#fde68a',
        'sidebar-border': '#404040',
        'sidebar-ring': '#f59e0b',
      },
    },
  },

  supabase: {
    label: 'Supabase',
    createdAt: '2025-04-27',
    styles: {
      light: {
        background: '#fcfcfc',
        foreground: '#171717',
        card: '#fcfcfc',
        'card-foreground': '#171717',
        popover: '#fcfcfc',
        'popover-foreground': '#525252',
        primary: '#72e3ad',
        'primary-foreground': '#1e2723',
        secondary: '#fdfdfd',
        'secondary-foreground': '#171717',
        muted: '#ededed',
        'muted-foreground': '#202020',
        accent: '#ededed',
        'accent-foreground': '#202020',
        destructive: '#ca3214',
        'destructive-foreground': '#fffcfc',
        border: '#dfdfdf',
        input: '#f6f6f6',
        ring: '#72e3ad',
        'chart-1': '#72e3ad',
        'chart-2': '#3b82f6',
        'chart-3': '#8b5cf6',
        'chart-4': '#f59e0b',
        'chart-5': '#10b981',
        sidebar: '#fcfcfc',
        'sidebar-foreground': '#707070',
        'sidebar-primary': '#72e3ad',
        'sidebar-primary-foreground': '#1e2723',
        'sidebar-accent': '#ededed',
        'sidebar-accent-foreground': '#202020',
        'sidebar-border': '#dfdfdf',
        'sidebar-ring': '#72e3ad',
        'font-sans': 'Outfit, sans-serif',
        'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': 'monospace',
        radius: '0.5rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.17',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
        'letter-spacing': '0.025em',
      },
      dark: {
        background: '#121212',
        foreground: '#e2e8f0',
        card: '#171717',
        'card-foreground': '#e2e8f0',
        popover: '#242424',
        'popover-foreground': '#a9a9a9',
        primary: '#006239',
        'primary-foreground': '#dde8e3',
        secondary: '#242424',
        'secondary-foreground': '#fafafa',
        muted: '#1f1f1f',
        'muted-foreground': '#a2a2a2',
        accent: '#313131',
        'accent-foreground': '#fafafa',
        destructive: '#541c15',
        'destructive-foreground': '#ede9e8',
        border: '#292929',
        input: '#242424',
        ring: '#4ade80',
        'chart-1': '#4ade80',
        'chart-2': '#60a5fa',
        'chart-3': '#a78bfa',
        'chart-4': '#fbbf24',
        'chart-5': '#2dd4bf',
        sidebar: '#121212',
        'sidebar-foreground': '#898989',
        'sidebar-primary': '#006239',
        'sidebar-primary-foreground': '#dde8e3',
        'sidebar-accent': '#313131',
        'sidebar-accent-foreground': '#fafafa',
        'sidebar-border': '#292929',
        'sidebar-ring': '#4ade80',
      },
    },
  },

  'neo-brutalism': {
    label: 'Neo Brutalism',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#000000',
        card: '#ffffff',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#ff3333',
        'primary-foreground': '#ffffff',
        secondary: '#ffff00',
        'secondary-foreground': '#000000',
        muted: '#f0f0f0',
        'muted-foreground': '#333333',
        accent: '#0066ff',
        'accent-foreground': '#ffffff',
        destructive: '#000000',
        'destructive-foreground': '#ffffff',
        border: '#000000',
        input: '#000000',
        ring: '#ff3333',
        'chart-1': '#ff3333',
        'chart-2': '#ffff00',
        'chart-3': '#0066ff',
        'chart-4': '#00cc00',
        'chart-5': '#cc00cc',
        radius: '0px',
        sidebar: '#f0f0f0',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#ff3333',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#0066ff',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#000000',
        'sidebar-ring': '#ff3333',
        'font-sans': 'DM Sans, sans-serif',
        'font-mono': 'Space Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '1',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '4px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#000000',
        foreground: '#ffffff',
        card: '#333333',
        'card-foreground': '#ffffff',
        popover: '#333333',
        'popover-foreground': '#ffffff',
        primary: '#ff6666',
        'primary-foreground': '#000000',
        secondary: '#ffff33',
        'secondary-foreground': '#000000',
        muted: '#1a1a1a',
        'muted-foreground': '#cccccc',
        accent: '#3399ff',
        'accent-foreground': '#000000',
        destructive: '#ffffff',
        'destructive-foreground': '#000000',
        border: '#ffffff',
        input: '#ffffff',
        ring: '#ff6666',
        'chart-1': '#ff6666',
        'chart-2': '#ffff33',
        'chart-3': '#3399ff',
        'chart-4': '#33cc33',
        'chart-5': '#cc33cc',
        radius: '0px',
        sidebar: '#000000',
        'sidebar-foreground': '#ffffff',
        'sidebar-primary': '#ff6666',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#3399ff',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ffffff',
        'sidebar-ring': '#ff6666',
      },
    },
  },
}
