// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk A: presets 1-4.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkA: Record<string, ThemePreset> = {
  'modern-minimal': {
    label: 'Modern Minimal',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        radius: '0.375rem',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      },
    },
  },

  'violet-bloom': {
    label: 'Violet Bloom',
    createdAt: '2025-06-26',
    styles: {
      light: {
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        'destructive-foreground': '#ffffff',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#000000',
        'chart-1': '#4ac885',
        'chart-2': '#7033ff',
        'chart-3': '#fd822b',
        'chart-4': '#3276e4',
        'chart-5': '#747474',
        sidebar: '#f5f8fb',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ebebeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#000000',
        'font-sans': 'Plus Jakarta Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
      dark: {
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        'chart-1': '#4ade80',
        'chart-2': '#8c5cff',
        'chart-3': '#fca5a5',
        'chart-4': '#5993f4',
        'chart-5': '#a0a0a0',
        sidebar: '#161618',
        'sidebar-foreground': '#f0f0f0',
        'sidebar-primary': '#8c5cff',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a2c33',
        'sidebar-accent-foreground': '#8c5cff',
        'sidebar-border': '#33353a',
        'sidebar-ring': '#8c5cff',
        'font-sans': 'Plus Jakarta Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
    },
  },

  't3-chat': {
    label: 'T3 Chat',
    createdAt: '2025-04-19',
    styles: {
      light: {
        background: '#faf5fa',
        foreground: '#501854',
        card: '#faf5fa',
        'card-foreground': '#501854',
        popover: '#ffffff',
        'popover-foreground': '#501854',
        primary: '#a84370',
        'primary-foreground': '#ffffff',
        secondary: '#f1c4e6',
        'secondary-foreground': '#77347c',
        muted: '#f6e5f3',
        'muted-foreground': '#834588',
        accent: '#f1c4e6',
        'accent-foreground': '#77347c',
        destructive: '#ab4347',
        'destructive-foreground': '#ffffff',
        border: '#efbdeb',
        input: '#e7c1dc',
        ring: '#db2777',
        'chart-1': '#d926a2',
        'chart-2': '#6c12b9',
        'chart-3': '#274754',
        'chart-4': '#e8c468',
        'chart-5': '#f4a462',
        sidebar: '#f3e4f6',
        'sidebar-foreground': '#ac1668',
        'sidebar-primary': '#454554',
        'sidebar-primary-foreground': '#faf1f7',
        'sidebar-accent': '#f8f8f7',
        'sidebar-accent-foreground': '#454554',
        'sidebar-border': '#eceae9',
        'sidebar-ring': '#db2777',
        radius: '0.5rem',
      },
      dark: {
        background: '#221d27',
        foreground: '#d2c4de',
        card: '#2c2632',
        'card-foreground': '#dbc5d2',
        popover: '#100a0e',
        'popover-foreground': '#f8f1f5',
        primary: '#a3004c',
        'primary-foreground': '#efc0d8',
        secondary: '#362d3d',
        'secondary-foreground': '#d4c7e1',
        muted: '#28222d',
        'muted-foreground': '#c2b6cf',
        accent: '#463753',
        'accent-foreground': '#f8f1f5',
        destructive: '#301015',
        'destructive-foreground': '#ffffff',
        border: '#3b3237',
        input: '#3e343c',
        ring: '#db2777',
        'chart-1': '#a84370',
        'chart-2': '#934dcb',
        'chart-3': '#e88c30',
        'chart-4': '#af57db',
        'chart-5': '#e23670',
        sidebar: '#181117',
        'sidebar-foreground': '#e0cad6',
        'sidebar-primary': '#1d4ed8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#261922',
        'sidebar-accent-foreground': '#f4f4f5',
        'sidebar-border': '#000000',
        'sidebar-ring': '#db2777',
      },
    },
  },

  twitter: {
    label: 'Twitter',
    createdAt: '2025-04-24',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#0f1419',
        card: '#f7f8f8',
        'card-foreground': '#0f1419',
        popover: '#ffffff',
        'popover-foreground': '#0f1419',
        primary: '#1e9df1',
        'primary-foreground': '#ffffff',
        secondary: '#0f1419',
        'secondary-foreground': '#ffffff',
        muted: '#E5E5E6',
        'muted-foreground': '#0f1419',
        accent: '#E3ECF6',
        'accent-foreground': '#1e9df1',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#e1eaef',
        input: '#f7f9fa',
        ring: '#1da1f2',
        'chart-1': '#1e9df1',
        'chart-2': '#00b87a',
        'chart-3': '#f7b928',
        'chart-4': '#17bf63',
        'chart-5': '#e0245e',
        sidebar: '#f7f8f8',
        'sidebar-foreground': '#0f1419',
        'sidebar-primary': '#1e9df1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#E3ECF6',
        'sidebar-accent-foreground': '#1e9df1',
        'sidebar-border': '#e1e8ed',
        'sidebar-ring': '#1da1f2',
        'font-sans': 'Open Sans, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Menlo, monospace',
        radius: '1.3rem',
        'shadow-color': 'rgba(29,161,242,0.15)',
        'shadow-opacity': '0',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#000000',
        foreground: '#e7e9ea',
        card: '#17181c',
        'card-foreground': '#d9d9d9',
        popover: '#000000',
        'popover-foreground': '#e7e9ea',
        primary: '#1c9cf0',
        'primary-foreground': '#ffffff',
        secondary: '#f0f3f4',
        'secondary-foreground': '#0f1419',
        muted: '#181818',
        'muted-foreground': '#72767a',
        accent: '#061622',
        'accent-foreground': '#1c9cf0',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#242628',
        input: '#22303c',
        ring: '#1da1f2',
        'chart-1': '#1e9df1',
        'chart-2': '#00b87a',
        'chart-3': '#f7b928',
        'chart-4': '#17bf63',
        'chart-5': '#e0245e',
        sidebar: '#17181c',
        'sidebar-foreground': '#d9d9d9',
        'sidebar-primary': '#1da1f2',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#061622',
        'sidebar-accent-foreground': '#1c9cf0',
        'sidebar-border': '#38444d',
        'sidebar-ring': '#1da1f2',
        'shadow-color': 'rgba(29,161,242,0.25)',
      },
    },
  },

  'mocha-mousse': {
    label: 'Mocha Mousse',
    createdAt: '2025-04-24',
    styles: {
      light: {
        background: '#F1F0E5',
        foreground: '#56453F',
        card: '#F1F0E5',
        'card-foreground': '#56453F',
        popover: '#FFFFFF',
        'popover-foreground': '#56453F',
        primary: '#A37764',
        'primary-foreground': '#FFFFFF',
        secondary: '#BAAB92',
        'secondary-foreground': '#ffffff',
        muted: '#E4C7B8',
        'muted-foreground': '#8A655A',
        accent: '#E4C7B8',
        'accent-foreground': '#56453F',
        destructive: '#1f1a17',
        'destructive-foreground': '#FFFFFF',
        border: '#BAAB92',
        input: '#BAAB92',
        ring: '#A37764',
        'chart-1': '#A37764',
        'chart-2': '#8A655A',
        'chart-3': '#C39E88',
        'chart-4': '#BAAB92',
        'chart-5': '#A28777',
        sidebar: '#ebd6cb',
        'sidebar-foreground': '#56453F',
        'sidebar-primary': '#A37764',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#C39E88',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#A28777',
        'sidebar-ring': '#A37764',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Menlo, monospace',
        radius: '0.5rem',
        'shadow-color': 'hsl(20 18% 51% / 0.4)',
        'shadow-opacity': '0.11',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#2d2521',
        foreground: '#F1F0E5',
        card: '#3c332e',
        'card-foreground': '#F1F0E5',
        popover: '#3c332e',
        'popover-foreground': '#F1F0E5',
        primary: '#C39E88',
        'primary-foreground': '#2d2521',
        secondary: '#8A655A',
        'secondary-foreground': '#F1F0E5',
        muted: '#56453F',
        'muted-foreground': '#c5aa9b',
        accent: '#BAAB92',
        'accent-foreground': '#2d2521',
        destructive: '#E57373',
        'destructive-foreground': '#2d2521',
        border: '#56453F',
        input: '#56453F',
        ring: '#C39E88',
        'chart-1': '#C39E88',
        'chart-2': '#BAAB92',
        'chart-3': '#A37764',
        'chart-4': '#8A655A',
        'chart-5': '#A28777',
        sidebar: '#1f1a17',
        'sidebar-foreground': '#F1F0E5',
        'sidebar-primary': '#C39E88',
        'sidebar-primary-foreground': '#1f1a17',
        'sidebar-accent': '#BAAB92',
        'sidebar-accent-foreground': '#1f1a17',
        'sidebar-border': '#56453F',
        'sidebar-ring': '#C39E88',
        'shadow-color': 'hsl(20 18% 30% / 0.5)',
      },
    },
  },

  bubblegum: {
    label: 'Bubblegum',
    createdAt: '2025-04-18',
    styles: {
      light: {
        background: '#f6e6ee',
        foreground: '#5b5b5b',
        card: '#fdedc9',
        'card-foreground': '#5b5b5b',
        popover: '#ffffff',
        'popover-foreground': '#5b5b5b',
        primary: '#d04f99',
        'primary-foreground': '#ffffff',
        secondary: '#8acfd1',
        'secondary-foreground': '#333333',
        muted: '#b2e1eb',
        'muted-foreground': '#7a7a7a',
        accent: '#fbe2a7',
        'accent-foreground': '#333333',
        destructive: '#f96f70',
        'destructive-foreground': '#ffffff',
        border: '#d04f99',
        input: '#e4e4e4',
        ring: '#e670ab',
        'chart-1': '#e670ab',
        'chart-2': '#84d2e2',
        'chart-3': '#fbe2a7',
        'chart-4': '#f3a0ca',
        'chart-5': '#d7488e',
        sidebar: '#f8d8ea',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#ec4899',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f9a8d4',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#f3e8ff',
        'sidebar-ring': '#ec4899',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.4rem',
        'shadow-color': 'hsl(325.78 58.18% 56.86% / 0.5)',
        'shadow-opacity': '1.0',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '3px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#12242e',
        foreground: '#f3e3ea',
        card: '#1c2e38',
        'card-foreground': '#f3e3ea',
        popover: '#1c2e38',
        'popover-foreground': '#f3e3ea',
        primary: '#fbe2a7',
        'primary-foreground': '#12242e',
        secondary: '#e4a2b1',
        'secondary-foreground': '#12242e',
        muted: '#24272b',
        'muted-foreground': '#e4a2b1',
        accent: '#c67b96',
        'accent-foreground': '#f3e3ea',
        destructive: '#e35ea4',
        'destructive-foreground': '#12242e',
        border: '#324859',
        input: '#20333d',
        ring: '#50afb6',
        'chart-1': '#50afb6',
        'chart-2': '#e4a2b1',
        'chart-3': '#c67b96',
        'chart-4': '#175c6c',
        'chart-5': '#24272b',
        sidebar: '#101f28',
        'sidebar-foreground': '#f3f4f6',
        'sidebar-primary': '#ec4899',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f9a8d4',
        'sidebar-accent-foreground': '#1f2937',
        'sidebar-border': '#374151',
        'sidebar-ring': '#ec4899',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': '#324859',
      },
    },
  },
}
