// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk B: presets 5-6.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkB: Record<string, ThemePreset> = {
  'amethyst-haze': {
    label: 'Amethyst Haze',
    createdAt: '2025-05-08',
    styles: {
      light: {
        background: '#f8f7fa',
        foreground: '#3d3c4f',
        card: '#ffffff',
        'card-foreground': '#3d3c4f',
        popover: '#ffffff',
        'popover-foreground': '#3d3c4f',
        primary: '#8a79ab',
        'primary-foreground': '#f8f7fa',
        secondary: '#dfd9ec',
        'secondary-foreground': '#3d3c4f',
        muted: '#dcd9e3',
        'muted-foreground': '#6b6880',
        accent: '#e6a5b8',
        'accent-foreground': '#4b2e36',
        destructive: '#d95c5c',
        'destructive-foreground': '#f8f7fa',
        border: '#cec9d9',
        input: '#eae7f0',
        ring: '#8a79ab',
        'chart-1': '#8a79ab',
        'chart-2': '#e6a5b8',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        sidebar: '#f1eff5',
        'sidebar-foreground': '#3d3c4f',
        'sidebar-primary': '#8a79ab',
        'sidebar-primary-foreground': '#f8f7fa',
        'sidebar-accent': '#e6a5b8',
        'sidebar-accent-foreground': '#4b2e36',
        'sidebar-border': '#d7d2e0',
        'sidebar-ring': '#8a79ab',
        'font-sans': 'Geist, sans-serif',
        'font-serif': '"Lora", Georgia, serif',
        'font-mono': '"Fira Code", "Courier New", monospace',
        radius: '0.5rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.06',
        'shadow-blur': '5px',
        'shadow-spread': '1px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#1a1823',
        foreground: '#e0ddef',
        card: '#232030',
        'card-foreground': '#e0ddef',
        popover: '#232030',
        'popover-foreground': '#e0ddef',
        primary: '#a995c9',
        'primary-foreground': '#1a1823',
        secondary: '#5a5370',
        'secondary-foreground': '#e0ddef',
        muted: '#242031',
        'muted-foreground': '#a09aad',
        accent: '#372e3f',
        'accent-foreground': '#f2b8c6',
        destructive: '#e57373',
        'destructive-foreground': '#1a1823',
        border: '#302c40',
        input: '#2a273a',
        ring: '#a995c9',
        'chart-1': '#a995c9',
        'chart-2': '#f2b8c6',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        sidebar: '#16141e',
        'sidebar-foreground': '#e0ddef',
        'sidebar-primary': '#a995c9',
        'sidebar-primary-foreground': '#1a1823',
        'sidebar-accent': '#372e3f',
        'sidebar-accent-foreground': '#f2b8c6',
        'sidebar-border': '#2a273a',
        'sidebar-ring': '#a995c9',
      },
    },
  },

  notebook: {
    label: 'Notebook',
    createdAt: '2025-05-10',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#3a3a3a',
        card: '#ffffff',
        'card-foreground': '#3a3a3a',
        popover: '#ffffff',
        'popover-foreground': '#3a3a3a',
        primary: '#606060',
        'primary-foreground': '#f0f0f0',
        secondary: '#dedede',
        'secondary-foreground': '#3a3a3a',
        muted: '#e3e3e3',
        'muted-foreground': '#505050',
        accent: '#f3eac8',
        'accent-foreground': '#5d4037',
        destructive: '#c87a7a',
        'destructive-foreground': '#ffffff',
        border: '#747272',
        input: '#ffffff',
        ring: '#a0a0a0',
        'chart-1': '#333333',
        'chart-2': '#555555',
        'chart-3': '#777777',
        'chart-4': '#999999',
        'chart-5': '#bbbbbb',
        sidebar: '#f0f0f0',
        'sidebar-foreground': '#3a3a3a',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#f0f0f0',
        'sidebar-accent': '#f3eac8',
        'sidebar-accent-foreground': '#5d4037',
        'sidebar-border': '#c0c0c0',
        'sidebar-ring': '#a0a0a0',
        'font-sans': 'Architects Daughter, sans-serif',
        'font-serif': '"Times New Roman", Times, serif',
        'font-mono': '"Courier New", Courier, monospace',
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
      dark: {
        background: '#2b2b2b',
        foreground: '#dcdcdc',
        card: '#333333',
        'card-foreground': '#dcdcdc',
        popover: '#333333',
        'popover-foreground': '#dcdcdc',
        primary: '#b0b0b0',
        'primary-foreground': '#2b2b2b',
        secondary: '#5a5a5a',
        'secondary-foreground': '#c0c0c0',
        muted: '#454545',
        'muted-foreground': '#a0a0a0',
        accent: '#e0e0e0',
        'accent-foreground': '#333333',
        destructive: '#d9afaf',
        'destructive-foreground': '#2b2b2b',
        border: '#4f4f4f',
        input: '#333333',
        ring: '#c0c0c0',
        'chart-1': '#efefef',
        'chart-2': '#d0d0d0',
        'chart-3': '#b0b0b0',
        'chart-4': '#909090',
        'chart-5': '#707070',
        sidebar: '#212121',
        'sidebar-foreground': '#dcdcdc',
        'sidebar-primary': '#b0b0b0',
        'sidebar-primary-foreground': '#212121',
        'sidebar-accent': '#e0e0e0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#4f4f4f',
        'sidebar-ring': '#c0c0c0',
        'font-sans': 'Architects Daughter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': '"Fira Code", "Courier New", monospace',
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
    },
  },

  'doom-64': {
    label: 'Doom 64',
    createdAt: '2025-04-28',
    styles: {
      light: {
        background: '#cccccc',
        foreground: '#1f1f1f',
        card: '#b0b0b0',
        'card-foreground': '#1f1f1f',
        popover: '#b0b0b0',
        'popover-foreground': '#1f1f1f',
        primary: '#b71c1c',
        'primary-foreground': '#ffffff',
        secondary: '#556b2f',
        'secondary-foreground': '#ffffff',
        muted: '#b8b8b8',
        'muted-foreground': '#4a4a4a',
        accent: '#4682b4',
        'accent-foreground': '#ffffff',
        destructive: '#ff6f00',
        'destructive-foreground': '#000000',
        border: '#505050',
        input: '#505050',
        ring: '#b71c1c',
        'chart-1': '#b71c1c',
        'chart-2': '#556b2f',
        'chart-3': '#4682b4',
        'chart-4': '#ff6f00',
        'chart-5': '#8d6e63',
        sidebar: '#b0b0b0',
        'sidebar-foreground': '#1f1f1f',
        'sidebar-primary': '#b71c1c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#4682b4',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#505050',
        'sidebar-ring': '#b71c1c',
        'font-sans': '"Oxanium", sans-serif',
        'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': '"Source Code Pro", monospace',
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.4',
        'shadow-blur': '4px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#e0e0e0',
        card: '#2a2a2a',
        'card-foreground': '#e0e0e0',
        popover: '#2a2a2a',
        'popover-foreground': '#e0e0e0',
        primary: '#e53935',
        'primary-foreground': '#ffffff',
        secondary: '#689f38',
        'secondary-foreground': '#000000',
        muted: '#252525',
        'muted-foreground': '#a0a0a0',
        accent: '#64b5f6',
        'accent-foreground': '#000000',
        destructive: '#ffa000',
        'destructive-foreground': '#000000',
        border: '#4a4a4a',
        input: '#4a4a4a',
        ring: '#e53935',
        'chart-1': '#e53935',
        'chart-2': '#689f38',
        'chart-3': '#64b5f6',
        'chart-4': '#ffa000',
        'chart-5': '#a1887f',
        sidebar: '#141414',
        'sidebar-foreground': '#e0e0e0',
        'sidebar-primary': '#e53935',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#64b5f6',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#4a4a4a',
        'sidebar-ring': '#e53935',
        'font-sans': '"Oxanium", sans-serif',
        'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': '"Source Code Pro", monospace',
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.6',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
    },
  },

  catppuccin: {
    label: 'Catppuccin',
    createdAt: '2025-04-18',
    styles: {
      light: {
        background: '#eff1f5',
        foreground: '#4c4f69',
        card: '#ffffff',
        'card-foreground': '#4c4f69',
        popover: '#ccd0da',
        'popover-foreground': '#4c4f69',
        primary: '#8839ef',
        'primary-foreground': '#ffffff',
        secondary: '#ccd0da',
        'secondary-foreground': '#4c4f69',
        muted: '#dce0e8',
        'muted-foreground': '#6c6f85',
        accent: '#04a5e5',
        'accent-foreground': '#ffffff',
        destructive: '#d20f39',
        'destructive-foreground': '#ffffff',
        border: '#bcc0cc',
        input: '#ccd0da',
        ring: '#8839ef',
        'chart-1': '#8839ef',
        'chart-2': '#04a5e5',
        'chart-3': '#40a02b',
        'chart-4': '#fe640b',
        'chart-5': '#dc8a78',
        sidebar: '#e6e9ef',
        'sidebar-foreground': '#4c4f69',
        'sidebar-primary': '#8839ef',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#04a5e5',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#bcc0cc',
        'sidebar-ring': '#8839ef',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.35rem',
        'shadow-color': 'hsl(240 30% 25%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '6px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#181825',
        foreground: '#cdd6f4',
        card: '#1e1e2e',
        'card-foreground': '#cdd6f4',
        popover: '#45475a',
        'popover-foreground': '#cdd6f4',
        primary: '#cba6f7',
        'primary-foreground': '#1e1e2e',
        secondary: '#585b70',
        'secondary-foreground': '#cdd6f4',
        muted: '#292c3c',
        'muted-foreground': '#a6adc8',
        accent: '#89dceb',
        'accent-foreground': '#1e1e2e',
        destructive: '#f38ba8',
        'destructive-foreground': '#1e1e2e',
        border: '#313244',
        input: '#313244',
        ring: '#cba6f7',
        'chart-1': '#cba6f7',
        'chart-2': '#89dceb',
        'chart-3': '#a6e3a1',
        'chart-4': '#fab387',
        'chart-5': '#f5e0dc',
        sidebar: '#11111b',
        'sidebar-foreground': '#cdd6f4',
        'sidebar-primary': '#cba6f7',
        'sidebar-primary-foreground': '#1e1e2e',
        'sidebar-accent': '#89dceb',
        'sidebar-accent-foreground': '#1e1e2e',
        'sidebar-border': '#45475a',
        'sidebar-ring': '#cba6f7',
      },
    },
  },

  graphite: {
    label: 'Graphite',
    createdAt: '2025-04-17',
    styles: {
      light: {
        background: '#f0f0f0',
        foreground: '#333333',
        card: '#f5f5f5',
        'card-foreground': '#333333',
        popover: '#f5f5f5',
        'popover-foreground': '#333333',
        primary: '#606060',
        'primary-foreground': '#ffffff',
        secondary: '#e0e0e0',
        'secondary-foreground': '#333333',
        muted: '#d9d9d9',
        'muted-foreground': '#666666',
        accent: '#c0c0c0',
        'accent-foreground': '#333333',
        destructive: '#cc3333',
        'destructive-foreground': '#ffffff',
        border: '#d0d0d0',
        input: '#e0e0e0',
        ring: '#606060',
        'chart-1': '#606060',
        'chart-2': '#476666',
        'chart-3': '#909090',
        'chart-4': '#a8a8a8',
        'chart-5': '#c0c0c0',
        sidebar: '#eaeaea',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#c0c0c0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#d0d0d0',
        'sidebar-ring': '#606060',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.35rem',
        'shadow-color': 'hsl(0 0% 20% / 0.1)',
        'shadow-opacity': '0.15',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#d9d9d9',
        card: '#202020',
        'card-foreground': '#d9d9d9',
        popover: '#202020',
        'popover-foreground': '#d9d9d9',
        primary: '#a0a0a0',
        'primary-foreground': '#1a1a1a',
        secondary: '#303030',
        'secondary-foreground': '#d9d9d9',
        muted: '#2a2a2a',
        'muted-foreground': '#808080',
        accent: '#404040',
        'accent-foreground': '#d9d9d9',
        destructive: '#e06666',
        'destructive-foreground': '#ffffff',
        border: '#353535',
        input: '#303030',
        ring: '#a0a0a0',
        'chart-1': '#a0a0a0',
        'chart-2': '#7e9ca0',
        'chart-3': '#707070',
        'chart-4': '#585858',
        'chart-5': '#404040',
        sidebar: '#1f1f1f',
        'sidebar-foreground': '#d9d9d9',
        'sidebar-primary': '#a0a0a0',
        'sidebar-primary-foreground': '#1a1a1a',
        'sidebar-accent': '#404040',
        'sidebar-accent-foreground': '#d9d9d9',
        'sidebar-border': '#353535',
        'sidebar-ring': '#a0a0a0',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
      },
    },
  },

  perpetuity: {
    label: 'Perpetuity',
    createdAt: '2025-04-01',
    styles: {
      light: {
        background: '#e8f0f0',
        foreground: '#0a4a55',
        card: '#f2f7f7',
        'card-foreground': '#0a4a55',
        popover: '#f2f7f7',
        'popover-foreground': '#0a4a55',
        primary: '#06858e',
        'primary-foreground': '#ffffff',
        secondary: '#d9eaea',
        'secondary-foreground': '#0a4a55',
        muted: '#e0eaea',
        'muted-foreground': '#427a7e',
        accent: '#c9e5e7',
        'accent-foreground': '#0a4a55',
        destructive: '#d13838',
        'destructive-foreground': '#ffffff',
        border: '#cde0e2',
        input: '#d9eaea',
        ring: '#06858e',
        'chart-1': '#06858e',
        'chart-2': '#1e9ea6',
        'chart-3': '#37b6be',
        'chart-4': '#5dc7ce',
        'chart-5': '#8ad8dd',
        sidebar: '#daebed',
        'sidebar-foreground': '#0a4a55',
        'sidebar-primary': '#06858e',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#c9e5e7',
        'sidebar-accent-foreground': '#0a4a55',
        'sidebar-border': '#cde0e2',
        'sidebar-ring': '#06858e',
        'font-sans': 'Courier New, monospace',
        'font-serif': 'Courier New, monospace',
        'font-mono': 'Courier New, monospace',
        radius: '0.125rem',
        'shadow-color': 'hsl(185 70% 30% / 0.15)',
        'shadow-opacity': '0.15',
        'shadow-blur': '2px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#0a1a20',
        foreground: '#4de8e8',
        card: '#0c2025',
        'card-foreground': '#4de8e8',
        popover: '#0c2025',
        'popover-foreground': '#4de8e8',
        primary: '#4de8e8',
        'primary-foreground': '#0a1a20',
        secondary: '#164955',
        'secondary-foreground': '#4de8e8',
        muted: '#0f3039',
        'muted-foreground': '#36a5a5',
        accent: '#164955',
        'accent-foreground': '#4de8e8',
        destructive: '#e83c3c',
        'destructive-foreground': '#f2f2f2',
        border: '#164955',
        input: '#164955',
        ring: '#4de8e8',
        'chart-1': '#4de8e8',
        'chart-2': '#36a5a5',
        'chart-3': '#2d8a8a',
        'chart-4': '#19595e',
        'chart-5': '#0e383c',
        sidebar: '#0a1a20',
        'sidebar-foreground': '#4de8e8',
        'sidebar-primary': '#4de8e8',
        'sidebar-primary-foreground': '#0a1a20',
        'sidebar-accent': '#164955',
        'sidebar-accent-foreground': '#4de8e8',
        'sidebar-border': '#164955',
        'sidebar-ring': '#4de8e8',
        'font-sans': 'Source Code Pro, monospace',
        'font-serif': 'Source Code Pro, monospace',
        'font-mono': 'Source Code Pro, monospace',
        radius: '0.125rem',
        'shadow-color': 'hsl(180 70% 60% / 0.2)',
        'shadow-opacity': '0.2',
        'shadow-blur': '2px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '1px',
      },
    },
  },
}
