// RESEARCH: tweakcn (Apache-2.0) — copied from utils/theme-presets.ts
// See NOTICE.md. Chunk E: presets 14-16.
// ADAPT: split into chunks to satisfy max-lines ESLint rule (600).

import type { ThemePreset } from '@/lib/design/contract/theme'

export const presetsChunkE: Record<string, ThemePreset> = {
  'solar-dusk': {
    label: 'Solar Dusk',
    createdAt: '2025-04-12',
    styles: {
      light: {
        background: '#FDFBF7',
        foreground: '#4A3B33',
        card: '#F8F4EE',
        'card-foreground': '#4A3B33',
        popover: '#F8F4EE',
        'popover-foreground': '#4A3B33',
        primary: '#B45309',
        'primary-foreground': '#FFFFFF',
        secondary: '#E4C090',
        'secondary-foreground': '#57534E',
        muted: '#F1E9DA',
        'muted-foreground': '#78716C',
        accent: '#f2daba',
        'accent-foreground': '#57534E',
        destructive: '#991B1B',
        'destructive-foreground': '#FFFFFF',
        border: '#E4D9BC',
        input: '#E4D9BC',
        ring: '#B45309',
        'chart-1': '#B45309',
        'chart-2': '#78716C',
        'chart-3': '#A16207',
        'chart-4': '#78716C',
        'chart-5': '#CA8A04',
        radius: '0.3rem',
        sidebar: '#F1E9DA',
        'sidebar-foreground': '#4A3B33',
        'sidebar-primary': '#B45309',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#A16207',
        'sidebar-accent-foreground': '#FFFFFF',
        'sidebar-border': '#E4D9BC',
        'sidebar-ring': '#B45309',
        'font-sans': 'Oxanium, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': 'hsl(28 18% 25%)',
        'shadow-opacity': '0.18',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1C1917',
        foreground: '#F5F5F4',
        card: '#292524',
        'card-foreground': '#F5F5F4',
        popover: '#292524',
        'popover-foreground': '#F5F5F4',
        primary: '#F97316',
        'primary-foreground': '#FFFFFF',
        secondary: '#57534E',
        'secondary-foreground': '#E7E5E4',
        muted: '#201d1a',
        'muted-foreground': '#A8A29E',
        accent: '#1e4252',
        'accent-foreground': '#E7E5E4',
        destructive: '#DC2626',
        'destructive-foreground': '#FFFFFF',
        border: '#44403C',
        input: '#44403C',
        ring: '#F97316',
        'chart-1': '#F97316',
        'chart-2': '#0EA5E9',
        'chart-3': '#EAB308',
        'chart-4': '#A8A29E',
        'chart-5': '#78716C',
        radius: '0.3rem',
        sidebar: '#292524',
        'sidebar-foreground': '#F5F5F4',
        'sidebar-primary': '#F97316',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#0EA5E9',
        'sidebar-accent-foreground': '#0C2A4D',
        'sidebar-border': '#44403C',
        'sidebar-ring': '#F97316',
        'shadow-color': 'hsl(0 0% 5%)',
      },
    },
  },

  claymorphism: {
    label: 'Claymorphism',
    styles: {
      light: {
        background: '#e7e5e4',
        foreground: '#1e293b',
        card: '#f5f5f4',
        'card-foreground': '#1e293b',
        popover: '#f5f5f4',
        'popover-foreground': '#1e293b',
        primary: '#6366f1',
        'primary-foreground': '#ffffff',
        secondary: '#d6d3d1',
        'secondary-foreground': '#4b5563',
        muted: '#e7e5e4',
        'muted-foreground': '#6b7280',
        accent: '#f3e5f5',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d6d3d1',
        input: '#d6d3d1',
        ring: '#6366f1',
        'chart-1': '#6366f1',
        'chart-2': '#4f46e5',
        'chart-3': '#4338ca',
        'chart-4': '#3730a3',
        'chart-5': '#312e81',
        radius: '1.25rem',
        sidebar: '#d6d3d1',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f3e5f5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#d6d3d1',
        'sidebar-ring': '#6366f1',
        'font-sans': 'Plus Jakarta Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Roboto Mono, monospace',
        'shadow-color': 'hsl(240 4% 60%)',
        'shadow-opacity': '0.18',
        'shadow-blur': '10px',
        'shadow-spread': '4px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1e1b18',
        foreground: '#e2e8f0',
        card: '#2c2825',
        'card-foreground': '#e2e8f0',
        popover: '#2c2825',
        'popover-foreground': '#e2e8f0',
        primary: '#818cf8',
        'primary-foreground': '#1e1b18',
        secondary: '#3a3633',
        'secondary-foreground': '#d1d5db',
        muted: '#1f1c19',
        'muted-foreground': '#9ca3af',
        accent: '#484441',
        'accent-foreground': '#d1d5db',
        destructive: '#ef4444',
        'destructive-foreground': '#1e1b18',
        border: '#3a3633',
        input: '#3a3633',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#4f46e5',
        'chart-4': '#4338ca',
        'chart-5': '#3730a3',
        radius: '1.25rem',
        sidebar: '#3a3633',
        'sidebar-foreground': '#e2e8f0',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#1e1b18',
        'sidebar-accent': '#484441',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#3a3633',
        'sidebar-ring': '#818cf8',
        'shadow-color': 'hsl(0 0% 0%)',
      },
    },
  },

  cyberpunk: {
    label: 'Cyberpunk',
    styles: {
      light: {
        background: '#f8f9fa',
        foreground: '#0c0c1d',
        card: '#ffffff',
        'card-foreground': '#0c0c1d',
        popover: '#ffffff',
        'popover-foreground': '#0c0c1d',
        primary: '#ff00c8',
        'primary-foreground': '#ffffff',
        secondary: '#f0f0ff',
        'secondary-foreground': '#0c0c1d',
        muted: '#f0f0ff',
        'muted-foreground': '#0c0c1d',
        accent: '#00ffcc',
        'accent-foreground': '#0c0c1d',
        destructive: '#ff3d00',
        'destructive-foreground': '#ffffff',
        border: '#dfe6e9',
        input: '#dfe6e9',
        ring: '#ff00c8',
        'chart-1': '#ff00c8',
        'chart-2': '#9000ff',
        'chart-3': '#00e5ff',
        'chart-4': '#00ffcc',
        'chart-5': '#ffe600',
        radius: '0.5rem',
        sidebar: '#f0f0ff',
        'sidebar-foreground': '#0c0c1d',
        'sidebar-primary': '#ff00c8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#00ffcc',
        'sidebar-accent-foreground': '#0c0c1d',
        'sidebar-border': '#dfe6e9',
        'sidebar-ring': '#ff00c8',
        'font-sans': 'Outfit, sans-serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-2px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0c0c1d',
        foreground: '#eceff4',
        card: '#1e1e3f',
        'card-foreground': '#eceff4',
        popover: '#1e1e3f',
        'popover-foreground': '#eceff4',
        primary: '#ff00c8',
        'primary-foreground': '#ffffff',
        secondary: '#1e1e3f',
        'secondary-foreground': '#eceff4',
        muted: '#151530',
        'muted-foreground': '#8085a6',
        accent: '#00ffcc',
        'accent-foreground': '#0c0c1d',
        destructive: '#ff3d00',
        'destructive-foreground': '#ffffff',
        border: '#2e2e5e',
        input: '#2e2e5e',
        ring: '#ff00c8',
        'chart-1': '#ff00c8',
        'chart-2': '#9000ff',
        'chart-3': '#00e5ff',
        'chart-4': '#00ffcc',
        'chart-5': '#ffe600',
        radius: '0.5rem',
        sidebar: '#0c0c1d',
        'sidebar-foreground': '#eceff4',
        'sidebar-primary': '#ff00c8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#00ffcc',
        'sidebar-accent-foreground': '#0c0c1d',
        'sidebar-border': '#2e2e5e',
        'sidebar-ring': '#ff00c8',
      },
    },
  },
  'pastel-dreams': {
    label: 'Pastel Dreams',
    styles: {
      light: {
        background: '#f7f3f9',
        foreground: '#374151',
        card: '#ffffff',
        'card-foreground': '#374151',
        popover: '#ffffff',
        'popover-foreground': '#374151',
        primary: '#a78bfa',
        'primary-foreground': '#ffffff',
        secondary: '#e9d8fd',
        'secondary-foreground': '#4b5563',
        muted: '#f3e8ff',
        'muted-foreground': '#6b7280',
        accent: '#f3e5f5',
        'accent-foreground': '#374151',
        destructive: '#fca5a5',
        'destructive-foreground': '#ffffff',
        border: '#e9d8fd',
        input: '#e9d8fd',
        ring: '#a78bfa',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#7c3aed',
        'chart-4': '#6d28d9',
        'chart-5': '#5b21b6',
        radius: '1.5rem',
        sidebar: '#e9d8fd',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#a78bfa',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f3e5f5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e9d8fd',
        'sidebar-ring': '#a78bfa',
        'font-sans': 'Open Sans, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.08',
        'shadow-blur': '16px',
        'shadow-spread': '-4px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '8px',
      },
      dark: {
        background: '#1c1917',
        foreground: '#e0e7ff',
        card: '#2d2535',
        'card-foreground': '#e0e7ff',
        popover: '#2d2535',
        'popover-foreground': '#e0e7ff',
        primary: '#c0aafd',
        'primary-foreground': '#1c1917',
        secondary: '#3f324a',
        'secondary-foreground': '#d1d5db',
        muted: '#20182b',
        'muted-foreground': '#9ca3af',
        accent: '#4a3d5a',
        'accent-foreground': '#d1d5db',
        destructive: '#fca5a5',
        'destructive-foreground': '#1c1917',
        border: '#3f324a',
        input: '#3f324a',
        ring: '#c0aafd',
        'chart-1': '#c0aafd',
        'chart-2': '#a78bfa',
        'chart-3': '#8b5cf6',
        'chart-4': '#7c3aed',
        'chart-5': '#6d28d9',
        radius: '1.5rem',
        sidebar: '#3f324a',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#c0aafd',
        'sidebar-primary-foreground': '#1c1917',
        'sidebar-accent': '#4a3d5a',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#3f324a',
        'sidebar-ring': '#c0aafd',
      },
    },
  },

  'clean-slate': {
    label: 'Clean Slate',
    styles: {
      light: {
        background: '#f8fafc',
        foreground: '#1e293b',
        card: '#ffffff',
        'card-foreground': '#1e293b',
        popover: '#ffffff',
        'popover-foreground': '#1e293b',
        primary: '#6366f1',
        'primary-foreground': '#ffffff',
        secondary: '#e5e7eb',
        'secondary-foreground': '#374151',
        muted: '#f3f4f6',
        'muted-foreground': '#6b7280',
        accent: '#e0e7ff',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d1d5db',
        input: '#d1d5db',
        ring: '#6366f1',
        'chart-1': '#6366f1',
        'chart-2': '#4f46e5',
        'chart-3': '#4338ca',
        'chart-4': '#3730a3',
        'chart-5': '#312e81',
        radius: '0.5rem',
        sidebar: '#f3f4f6',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0e7ff',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#d1d5db',
        'sidebar-ring': '#6366f1',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'JetBrains Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f172a',
        foreground: '#e2e8f0',
        card: '#1e293b',
        'card-foreground': '#e2e8f0',
        popover: '#1e293b',
        'popover-foreground': '#e2e8f0',
        primary: '#818cf8',
        'primary-foreground': '#0f172a',
        secondary: '#2d3748',
        'secondary-foreground': '#d1d5db',
        muted: '#152032',
        'muted-foreground': '#9ca3af',
        accent: '#374151',
        'accent-foreground': '#d1d5db',
        destructive: '#ef4444',
        'destructive-foreground': '#0f172a',
        border: '#4b5563',
        input: '#4b5563',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#4f46e5',
        'chart-4': '#4338ca',
        'chart-5': '#3730a3',
        radius: '0.5rem',
        sidebar: '#1e293b',
        'sidebar-foreground': '#e2e8f0',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#4b5563',
        'sidebar-ring': '#818cf8',
      },
    },
  },

  caffeine: {
    label: 'Caffeine',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#202020',
        card: '#fcfcfc',
        'card-foreground': '#202020',
        popover: '#fcfcfc',
        'popover-foreground': '#202020',
        primary: '#644a40',
        'primary-foreground': '#ffffff',
        secondary: '#ffdfb5',
        'secondary-foreground': '#582d1d',
        muted: '#efefef',
        'muted-foreground': '#646464',
        accent: '#e8e8e8',
        'accent-foreground': '#202020',
        destructive: '#e54d2e',
        'destructive-foreground': '#ffffff',
        border: '#d8d8d8',
        input: '#d8d8d8',
        ring: '#644a40',
        'chart-1': '#644a40',
        'chart-2': '#ffdfb5',
        'chart-3': '#e8e8e8',
        'chart-4': '#ffe6c4',
        'chart-5': '#66493e',
        sidebar: '#fbfbfb',
        'sidebar-foreground': '#252525',
        'sidebar-primary': '#343434',
        'sidebar-primary-foreground': '#fbfbfb',
        'sidebar-accent': '#f7f7f7',
        'sidebar-accent-foreground': '#343434',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#b5b5b5',
        radius: '0.5rem',
      },
      dark: {
        background: '#111111',
        foreground: '#eeeeee',
        card: '#191919',
        'card-foreground': '#eeeeee',
        popover: '#191919',
        'popover-foreground': '#eeeeee',
        primary: '#ffe0c2',
        'primary-foreground': '#081a1b',
        secondary: '#393028',
        'secondary-foreground': '#ffe0c2',
        muted: '#222222',
        'muted-foreground': '#b4b4b4',
        accent: '#2a2a2a',
        'accent-foreground': '#eeeeee',
        destructive: '#e54d2e',
        'destructive-foreground': '#ffffff',
        border: '#201e18',
        input: '#484848',
        ring: '#ffe0c2',
        'chart-1': '#ffe0c2',
        'chart-2': '#393028',
        'chart-3': '#2a2a2a',
        'chart-4': '#42382e',
        'chart-5': '#ffe0c1',
        sidebar: '#18181b',
        'sidebar-foreground': '#f4f4f5',
        'sidebar-primary': '#1d4ed8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#27272a',
        'sidebar-accent-foreground': '#f4f4f5',
        'sidebar-border': '#27272a',
        'sidebar-ring': '#d4d4d8',
        radius: '0.5rem',
      },
    },
  },
}
